# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from pathlib import Path
from typing import Any
import json
import logging
import math
import os
import random
import requests

requests = None
EBAY_OAUTH_URL = 'https://api.ebay.com/identity/v1/oauth2/token'
EBAY_BROWSE_URL = 'https://api.ebay.com/buy/browse/v1/item_summary/search'
_cached_token = None
_token_expiry = 0
def get_ebay_access_token() -> Any:
    ...

def search_ebay_listings(query: Any, limit: Any) -> Any:
    ...

def synthesize_history_from_listings(listings: Any) -> Any:
    ...

def get_market_depth(card_name: Any, limit: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import json
import logging
import math
import random
import datetime
import pathlib
import pathlib.Path
import requests
import time
import base64
import sys