# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from functools import lru_cache
from typing import Any
import torch

_classifier = None
def _get_classifier() -> Any:
    ...

def classify_emotion(text: str) -> list:
    ...

def compute_emotion_adjustments(emotions: list, soul_traits: dict) -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import torch
import functools
import transformers
import transformers.pipeline