# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from docker.errors import DockerException, ImageNotFound
from pathlib import Path
from typing import Any
from typing_extensions import Self
import ast
import docker
import logging
import os
import platform
import shutil
import signal
import subprocess
import sys
import uuid

HAS_DOCKER = True
DOCKER_CLIENT = None
HAS_DOCKER = False
DOCKER_CLIENT = None
HAS_DOCKER = False
SANDBOX_BASE = '/tmp/undsr_sandbox'
MAX_TIMEOUT = 15
MAX_OUTPUT = 10000
MAX_CODE_SIZE = 50000
DANGEROUS_PATTERNS = ['rm -rf', 'rm -r /', 'mkfs', 'dd if=', ':(){', 'sudo ', 'su ', '> /dev/', 'curl ', 'wget ', 'nc ', 'ncat ', 'open -a', 'osascript', 'defaults write', 'launchctl', 'killall', 'shutdown', 'reboot', 'halt', 'diskutil']
DANGEROUS_IMPORTS = ['subprocess', 'shutil.rmtree', 'os.system', 'os.popen', 'os.remove', 'os.unlink', 'os.rmdir', 'os.removedirs', 'socket', 'http.client', 'urllib.request', 'requests', 'smtplib', 'ftplib', 'telnetlib', 'ctypes', '__import__', 'importlib', 'exec(', 'eval(', 'compile(', 'globals(', 'locals(', 'getattr(', 'setattr(', 'os.environ', 'os.putenv', 'pathlib', 'shutil.copy', 'shutil.move']
class SandboxResult:
    def __init__(self: Self, stdout: str, stderr: str, exit_code: int, timed_out: bool, sandbox_dir: str) -> None: ...
    def to_dict(self: Self) -> dict: ...

BLOCKED_MODULES = {'subprocess', 'shutil', 'os', 'socket', 'http', 'urllib', 'requests', 'smtplib', 'ftplib', 'telnetlib', 'ctypes', 'importlib', 'pathlib'}
def _check_dangerous_code(code: str) -> str:
    ...

def execute_python(code: str, timeout: int) -> SandboxResult:
    ...

def execute_shell(command: str, timeout: int) -> SandboxResult:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import uuid
import shutil
import signal
import subprocess
import logging
import platform
import ast
import pathlib
import pathlib.Path
import docker
import docker.errors
import posixpath