# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from security import is_safe_symlink, validate_workspace_path
from typing import Any, List, Optional
import hashlib
import json
import logging
import numpy
import os
import re

_embedder = None
_db = None
_table = None
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100
TABLE_NAME = 'soul_memory'
def _get_embedder() -> Any:
    ...

def _get_db(workspace_path: str) -> Any:
    ...

def _chunk_text(text: str, source: str) -> List[dict]:
    ...

def _compute_file_hash(filepath: str) -> str:
    ...

def index_workspace(workspace_path: str) -> dict:
    ...

def search_memory(workspace_path: str, query: str, top_k: int) -> List[dict]:
    ...

def build_rag_context(workspace_path: str, query: str, max_tokens: int) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import re
import json
import hashlib
import logging
import numpy
import pathlib
import pathlib.Path
import typing
import security
import sentence_transformers
import sentence_transformers.SentenceTransformer
import torch
import lancedb
import posixpath
import ijson