# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import json
import os
import re
import sys
import time
import torch

_original_torch_load = torch.load
def _patched_load() -> Any:
    ...

def main() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import json
import os
import time
import re
import torch
import posixpath
import pathlib
import bark
import numpy
import scipy
import scipy.io
import scipy.io.wavfile