# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from PIL import Image, ImageFilter
from pathlib import Path
from server import validate_secure_path
from typing import Any
import json
import numpy
import os
import sys
import time

_SCRIPT_DIR = _Path(__file__).resolve().parent
def _validate_path(p: Any) -> Any:
    ...

def estimate_depth_from_image(img: Any) -> Any:
    ...

def create_mesh_from_depth(img: Any, depth: Any, resolution: Any, depth_scale: Any) -> Any:
    ...

def main() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import json
import os
import time
import numpy
import pathlib
import pathlib.Path
import server
import PIL
import PIL.Image
import PIL.ImageFilter
import colorsys
import trimesh
import posixpath