# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from pathlib import Path
from typing import Any
import csv
import json
import logging
import os
import requests
import sqlite3

CACHE_DIR = Path(__file__).parent / '.cache'
DB_PATH = CACHE_DIR / 'market_memory.sqlite'
CATEGORIES = {'magic': 1, 'pokemon': 3, 'yugioh': 2}
def init_db() -> Any:
    ...

def fetch_active_groups(category_id: Any) -> Any:
    ...

def snapshot_daily_prices(category_name: Any, max_groups: Any) -> Any:
    ...

def get_historical_volatility(card_name_query: Any) -> Any:
    ...

def import_shroomy_dataset(json_path: Any) -> Any:
    ...

def get_shroomy_stats(card_name_query: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sqlite3
import requests
import json
import csv
import logging
import datetime
import pathlib
import pathlib.Path
import math
import statistics
import sys