# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import logging
import os
import tempfile
import torch
import trimesh

_models = None
def _get_models() -> Any:
    ...

def generate_3d_from_text(prompt: str, output_path: str, guidance_scale: float, steps: int, batch_size: int) -> dict:
    ...

def generate_3d_from_image(image_path: str, output_path: str, guidance_scale: float, steps: int) -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import torch
import trimesh
import tempfile
import logging
import shap_e
import shap_e.diffusion
import shap_e.diffusion.sample
import shap_e.diffusion.gaussian_diffusion
import shap_e.models
import shap_e.models.download
import shap_e.util
import shap_e.util.notebooks
import security
import posixpath
import numpy
import PIL
import PIL.Image