# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any, Optional
import io
import logging
import os
import tempfile
import wave

_tts_pipeline = None
_stt_model = None
VOICE_PRESETS = {'warm_f': {'voice': 'af_heart', 'speed': 1.0}, 'warm_m': {'voice': 'am_michael', 'speed': 1.0}, 'assertive_f': {'voice': 'af_star', 'speed': 1.1}, 'assertive_m': {'voice': 'am_fenrir', 'speed': 1.1}, 'calm_f': {'voice': 'af_sky', 'speed': 0.9}, 'calm_m': {'voice': 'am_adam', 'speed': 0.9}, 'expressive_f': {'voice': 'af_bella', 'speed': 1.05}, 'expressive_m': {'voice': 'am_echo', 'speed': 1.05}, 'nervous_f': {'voice': 'af_nicole', 'speed': 1.15}, 'nervous_m': {'voice': 'am_eric', 'speed': 1.15}, 'default_f': {'voice': 'af_bella', 'speed': 1.0}, 'default_m': {'voice': 'am_adam', 'speed': 1.0}}
def _get_tts() -> Any:
    ...

def _get_stt() -> Any:
    ...

KOKORO_MALE = ['am_adam', 'am_michael', 'am_puck', 'am_onyx', 'am_echo']
KOKORO_FEMALE = ['af_heart', 'af_sky', 'af_bella', 'af_sarah', 'af_alloy']
def soul_to_voice_preset(traits: dict) -> dict:
    ...

def text_to_speech(text: str, output_path: str, voice: str, speed: float) -> dict:
    ...

def speech_to_text(audio_path: str) -> dict:
    ...

def text_to_speech_chunked(text: str, output_dir: str, voice: str, speed: float, max_chars: int) -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import io
import wave
import logging
import tempfile
import typing
import kokoro
import pywhispercpp
import pywhispercpp.model
import posixpath
import pathlib
import soundfile
import numpy
import re